I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 11, in script call
    call expression story_label pass (story_controller.get_story(story_label),npc)
  File "game/rpg_story/main_queen_labels.rpy", line 39, in script call
    $ battle_controller.start(npc)
  File "game/rpg_battle/01_battle_screen.rpy", line 9, in script call
    call start_battle_screen
  File "game/rpg_battle/01_battle_screen.rpy", line 13, in script
    call screen battle_screen
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/rpg_battle/01_battle_screen.rpy", line 21, in execute
    screen battle_screen:
  File "game/rpg_battle/01_battle_screen.rpy", line 21, in execute
    screen battle_screen:
  File "game/rpg_battle/01_battle_screen.rpy", line 107, in execute
    frame:
  File "game/rpg_battle/01_battle_screen.rpy", line 112, in execute
    hbox:
  File "game/rpg_battle/01_battle_screen.rpy", line 118, in execute
    for i,card in enumerate(battle_controller.player_hand):
  File "game/rpg_battle/01_battle_screen.rpy", line 119, in execute
    $ pos_i = i-hands_len/2
  File "game/rpg_battle/01_battle_screen.rpy", line 119, in <module>
    $ pos_i = i-hands_len/2
NameError: name 'hands_len' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 11, in script call
    call expression story_label pass (story_controller.get_story(story_label),npc)
  File "game/rpg_story/main_queen_labels.rpy", line 39, in script call
    $ battle_controller.start(npc)
  File "game/rpg_battle/01_battle_screen.rpy", line 9, in script call
    call start_battle_screen
  File "game/rpg_battle/01_battle_screen.rpy", line 13, in script
    call screen battle_screen
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/ast.py", line 1968, in execute
    self.call("execute")
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/exports.py", line 3413, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/core.py", line 2687, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 2 more times]
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/core.py", line 2687, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/display/screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/rpg_battle/01_battle_screen.rpy", line 21, in execute
    screen battle_screen:
  File "game/rpg_battle/01_battle_screen.rpy", line 21, in execute
    screen battle_screen:
  File "game/rpg_battle/01_battle_screen.rpy", line 107, in execute
    frame:
  File "game/rpg_battle/01_battle_screen.rpy", line 112, in execute
    hbox:
  File "game/rpg_battle/01_battle_screen.rpy", line 118, in execute
    for i,card in enumerate(battle_controller.player_hand):
  File "game/rpg_battle/01_battle_screen.rpy", line 119, in execute
    $ pos_i = i-hands_len/2
  File "game/rpg_battle/01_battle_screen.rpy", line 119, in <module>
    $ pos_i = i-hands_len/2
NameError: name 'hands_len' is not defined

Linux-6.5.0-35-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
Android GUI 1.31
Thu May 30 10:29:11 2024
